name: Workflow
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild Geo_ACAD_Lib.sln -t:rebuild -property:Configuration=Release
      
