name: Manual Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create and Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FOR /f %a IN ('WMIC OS GET LocalDateTime ^| FIND "."') DO SET DTS=%a
        SET tag=v%DTS:~0,8%
        gh release delete %tag% --yes --cleanup-tag
        gh release create %tag% --latest --notes "Created by Actions Workflow"
